linters:
  disable-all: true
  enable:
    # https://golangci-lint.run/usage/linters/#enabled-by-default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # https://golangci-lint.run/usage/linters/#disabled-by-default
    - gofmt
