FROM golang:1.22.3-alpine as build
ENV CGO_ENABLED 0
ENV TZ Asia/Tokyo

ARG GO_BUILD_TAGS=''
RUN echo $GO_BUILD_TAGS

RUN apk add --update --no-cache git
RUN apk --update --no-cache add tzdata \
    && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
    && apk del tzdata
RUN apk --update --no-cache add ca-certificates \
    && update-ca-certificates

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD [ "go", "run", "main.go" ]
