version: "3"

tasks:
  default:
    desc: Run the application (alias for run)
    cmds:
      - task: run

  run:
    desc: Run the built binary
    deps: [build]
    cmds:
      - /app/Jomon
    sources:
      - '**/*.go'

  build:
    desc: Build the Go application
    dir: /src
    cmds:
      - go build -tags debug -o /app/Jomon
