// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/traPtitech/Jomon/ent/runtime.go

const (
	Version = "v0.11.3-0.20220824145844-79fe0ebcd627"           // Version of ent codegen.
	Sum     = "h1:egVC7Wqsd5Yw9fbYrfOvTzqr1dMeAunS3tgUa528fHc=" // Sum of ent codegen.
)
