-- Create "groups" table
CREATE TABLE `groups` (`id` uuid NOT NULL, `name` varchar(255) NOT NULL, `description` varchar(255) NOT NULL, `budget` bigint NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, `deleted_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "users" table
CREATE TABLE `users` (`id` uuid NOT NULL, `name` varchar(255) NOT NULL, `display_name` varchar(255) NOT NULL, `account_manager` bool NOT NULL DEFAULT 0, `created_at` timestamp NULL, `updated_at` timestamp NULL, `deleted_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE INDEX `name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "applications" table
CREATE TABLE `applications` (`id` uuid NOT NULL, `title` varchar(255) NOT NULL, `content` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, `application_user` uuid NULL, `group_application` uuid NULL, PRIMARY KEY (`id`), INDEX `applications_groups_application` (`group_application`), INDEX `applications_users_user` (`application_user`), CONSTRAINT `applications_groups_application` FOREIGN KEY (`group_application`) REFERENCES `groups` (`id`) ON UPDATE RESTRICT ON DELETE SET NULL, CONSTRAINT `applications_users_user` FOREIGN KEY (`application_user`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "application_status" table
CREATE TABLE `application_status` (`id` uuid NOT NULL, `status` enum('submitted','fix_required','accepted','completed','rejected') NOT NULL DEFAULT 'submitted', `created_at` timestamp NULL, `application_status` uuid NOT NULL, `application_status_user` uuid NOT NULL, PRIMARY KEY (`id`), INDEX `application_status_applications_status` (`application_status`), INDEX `application_status_users_user` (`application_status_user`), CONSTRAINT `application_status_applications_status` FOREIGN KEY (`application_status`) REFERENCES `applications` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `application_status_users_user` FOREIGN KEY (`application_status_user`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "tags" table
CREATE TABLE `tags` (`id` uuid NOT NULL, `name` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, `deleted_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "application_tag" table
CREATE TABLE `application_tag` (`application_id` uuid NOT NULL, `tag_id` uuid NOT NULL, PRIMARY KEY (`application_id`, `tag_id`), INDEX `application_tag_tag_id` (`tag_id`), CONSTRAINT `application_tag_application_id` FOREIGN KEY (`application_id`) REFERENCES `applications` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `application_tag_tag_id` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "application_targets" table
CREATE TABLE `application_targets` (`id` uuid NOT NULL, `amount` bigint NOT NULL, `paid_at` timestamp NULL, `created_at` timestamp NULL, `application_target` uuid NOT NULL, `application_target_user` uuid NOT NULL, PRIMARY KEY (`id`), INDEX `application_targets_applications_target` (`application_target`), INDEX `application_targets_users_user` (`application_target_user`), CONSTRAINT `application_targets_applications_target` FOREIGN KEY (`application_target`) REFERENCES `applications` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `application_targets_users_user` FOREIGN KEY (`application_target_user`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "comments" table
CREATE TABLE `comments` (`id` uuid NOT NULL, `comment` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, `deleted_at` timestamp NULL, `application_comment` uuid NOT NULL, `comment_user` uuid NOT NULL, PRIMARY KEY (`id`), INDEX `comments_applications_comment` (`application_comment`), INDEX `comments_users_user` (`comment_user`), CONSTRAINT `comments_applications_comment` FOREIGN KEY (`application_comment`) REFERENCES `applications` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `comments_users_user` FOREIGN KEY (`comment_user`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "files" table
CREATE TABLE `files` (`id` uuid NOT NULL, `name` varchar(255) NOT NULL, `mime_type` varchar(255) NOT NULL, `created_at` timestamp NULL, `deleted_at` timestamp NULL, `application_file` uuid NULL, `file_user` uuid NOT NULL, PRIMARY KEY (`id`), INDEX `files_applications_file` (`application_file`), INDEX `files_users_user` (`file_user`), CONSTRAINT `files_applications_file` FOREIGN KEY (`application_file`) REFERENCES `applications` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `files_users_user` FOREIGN KEY (`file_user`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "group_budgets" table
CREATE TABLE `group_budgets` (`id` uuid NOT NULL, `amount` bigint NOT NULL, `comment` longtext NULL, `created_at` timestamp NULL, `group_group_budget` uuid NOT NULL, PRIMARY KEY (`id`), INDEX `group_budgets_groups_group_budget` (`group_group_budget`), CONSTRAINT `group_budgets_groups_group_budget` FOREIGN KEY (`group_group_budget`) REFERENCES `groups` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "group_owner" table
CREATE TABLE `group_owner` (`group_id` uuid NOT NULL, `user_id` uuid NOT NULL, PRIMARY KEY (`group_id`, `user_id`), INDEX `group_owner_user_id` (`user_id`), CONSTRAINT `group_owner_group_id` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `group_owner_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "group_user" table
CREATE TABLE `group_user` (`group_id` uuid NOT NULL, `user_id` uuid NOT NULL, PRIMARY KEY (`group_id`, `user_id`), INDEX `group_user_user_id` (`user_id`), CONSTRAINT `group_user_group_id` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `group_user_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "transactions" table
CREATE TABLE `transactions` (`id` uuid NOT NULL, `created_at` timestamp NULL, `application_transaction` uuid NULL, `group_budget_transaction` uuid NULL, PRIMARY KEY (`id`), INDEX `transactions_applications_transaction` (`application_transaction`), INDEX `transactions_group_budgets_transaction` (`group_budget_transaction`), CONSTRAINT `transactions_applications_transaction` FOREIGN KEY (`application_transaction`) REFERENCES `applications` (`id`) ON UPDATE RESTRICT ON DELETE SET NULL, CONSTRAINT `transactions_group_budgets_transaction` FOREIGN KEY (`group_budget_transaction`) REFERENCES `group_budgets` (`id`) ON UPDATE RESTRICT ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "transaction_details" table
CREATE TABLE `transaction_details` (`id` uuid NOT NULL, `title` varchar(64) NOT NULL, `amount` bigint NOT NULL DEFAULT 0, `target` varchar(255) NOT NULL DEFAULT '', `created_at` timestamp NULL, `updated_at` timestamp NULL, `transaction_detail` uuid NULL, PRIMARY KEY (`id`), UNIQUE INDEX `transaction_detail` (`transaction_detail`), CONSTRAINT `transaction_details_transactions_detail` FOREIGN KEY (`transaction_detail`) REFERENCES `transactions` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "transaction_tag" table
CREATE TABLE `transaction_tag` (`transaction_id` uuid NOT NULL, `tag_id` uuid NOT NULL, PRIMARY KEY (`transaction_id`, `tag_id`), INDEX `transaction_tag_tag_id` (`tag_id`), CONSTRAINT `transaction_tag_tag_id` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `transaction_tag_transaction_id` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
