-- Create "groups" table
CREATE TABLE `groups` (`id` uuid NOT NULL, `name` varchar(255) NOT NULL, `description` varchar(255) NOT NULL, `budget` bigint NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, `deleted_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "users" table
CREATE TABLE `users` (`id` uuid NOT NULL, `name` varchar(255) NOT NULL, `display_name` varchar(255) NOT NULL, `admin` bool NOT NULL DEFAULT 0, `created_at` timestamp NULL, `updated_at` timestamp NULL, `deleted_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE INDEX `name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "requests" table
CREATE TABLE `requests` (`id` uuid NOT NULL, `title` varchar(255) NOT NULL, `content` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, `group_request` uuid NULL, `request_user` uuid NULL, PRIMARY KEY (`id`), INDEX `requests_groups_request` (`group_request`), INDEX `requests_users_user` (`request_user`), CONSTRAINT `requests_groups_request` FOREIGN KEY (`group_request`) REFERENCES `groups` (`id`) ON UPDATE RESTRICT ON DELETE SET NULL, CONSTRAINT `requests_users_user` FOREIGN KEY (`request_user`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "comments" table
CREATE TABLE `comments` (`id` uuid NOT NULL, `comment` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, `deleted_at` timestamp NULL, `comment_user` uuid NOT NULL, `request_comment` uuid NOT NULL, PRIMARY KEY (`id`), INDEX `comments_requests_comment` (`request_comment`), INDEX `comments_users_user` (`comment_user`), CONSTRAINT `comments_requests_comment` FOREIGN KEY (`request_comment`) REFERENCES `requests` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `comments_users_user` FOREIGN KEY (`comment_user`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "files" table
CREATE TABLE `files` (`id` uuid NOT NULL, `name` varchar(255) NOT NULL, `mime_type` varchar(255) NOT NULL, `created_at` timestamp NULL, `deleted_at` timestamp NULL, `file_user` uuid NOT NULL, `request_file` uuid NULL, PRIMARY KEY (`id`), INDEX `files_requests_file` (`request_file`), INDEX `files_users_user` (`file_user`), CONSTRAINT `files_requests_file` FOREIGN KEY (`request_file`) REFERENCES `requests` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `files_users_user` FOREIGN KEY (`file_user`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "group_budgets" table
CREATE TABLE `group_budgets` (`id` uuid NOT NULL, `amount` bigint NOT NULL, `comment` longtext NULL, `created_at` timestamp NULL, `group_group_budget` uuid NOT NULL, PRIMARY KEY (`id`), INDEX `group_budgets_groups_group_budget` (`group_group_budget`), CONSTRAINT `group_budgets_groups_group_budget` FOREIGN KEY (`group_group_budget`) REFERENCES `groups` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "group_owner" table
CREATE TABLE `group_owner` (`group_id` uuid NOT NULL, `user_id` uuid NOT NULL, PRIMARY KEY (`group_id`, `user_id`), INDEX `group_owner_user_id` (`user_id`), CONSTRAINT `group_owner_group_id` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `group_owner_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "group_user" table
CREATE TABLE `group_user` (`group_id` uuid NOT NULL, `user_id` uuid NOT NULL, PRIMARY KEY (`group_id`, `user_id`), INDEX `group_user_user_id` (`user_id`), CONSTRAINT `group_user_group_id` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `group_user_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "request_status" table
CREATE TABLE `request_status` (`id` uuid NOT NULL, `status` enum('submitted','fix_required','accepted','completed','rejected') NOT NULL DEFAULT 'submitted', `created_at` timestamp NULL, `request_status` uuid NOT NULL, `request_status_user` uuid NOT NULL, PRIMARY KEY (`id`), INDEX `request_status_requests_status` (`request_status`), INDEX `request_status_users_user` (`request_status_user`), CONSTRAINT `request_status_requests_status` FOREIGN KEY (`request_status`) REFERENCES `requests` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `request_status_users_user` FOREIGN KEY (`request_status_user`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "tags" table
CREATE TABLE `tags` (`id` uuid NOT NULL, `name` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, `deleted_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "request_tag" table
CREATE TABLE `request_tag` (`request_id` uuid NOT NULL, `tag_id` uuid NOT NULL, PRIMARY KEY (`request_id`, `tag_id`), INDEX `request_tag_tag_id` (`tag_id`), CONSTRAINT `request_tag_request_id` FOREIGN KEY (`request_id`) REFERENCES `requests` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `request_tag_tag_id` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "request_targets" table
CREATE TABLE `request_targets` (`id` uuid NOT NULL, `amount` bigint NOT NULL, `paid_at` timestamp NULL, `created_at` timestamp NULL, `request_target` uuid NOT NULL, `request_target_user` uuid NOT NULL, PRIMARY KEY (`id`), INDEX `request_targets_requests_target` (`request_target`), INDEX `request_targets_users_user` (`request_target_user`), CONSTRAINT `request_targets_requests_target` FOREIGN KEY (`request_target`) REFERENCES `requests` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `request_targets_users_user` FOREIGN KEY (`request_target_user`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "transactions" table
CREATE TABLE `transactions` (`id` uuid NOT NULL, `created_at` timestamp NULL, `group_budget_transaction` uuid NULL, `request_transaction` uuid NULL, PRIMARY KEY (`id`), INDEX `transactions_group_budgets_transaction` (`group_budget_transaction`), INDEX `transactions_requests_transaction` (`request_transaction`), CONSTRAINT `transactions_group_budgets_transaction` FOREIGN KEY (`group_budget_transaction`) REFERENCES `group_budgets` (`id`) ON UPDATE RESTRICT ON DELETE SET NULL, CONSTRAINT `transactions_requests_transaction` FOREIGN KEY (`request_transaction`) REFERENCES `requests` (`id`) ON UPDATE RESTRICT ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "transaction_details" table
CREATE TABLE `transaction_details` (`id` uuid NOT NULL, `title` varchar(64) NOT NULL, `amount` bigint NOT NULL DEFAULT 0, `target` varchar(255) NOT NULL DEFAULT '', `created_at` timestamp NULL, `updated_at` timestamp NULL, `transaction_detail` uuid NULL, PRIMARY KEY (`id`), UNIQUE INDEX `transaction_detail` (`transaction_detail`), CONSTRAINT `transaction_details_transactions_detail` FOREIGN KEY (`transaction_detail`) REFERENCES `transactions` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "transaction_tag" table
CREATE TABLE `transaction_tag` (`transaction_id` uuid NOT NULL, `tag_id` uuid NOT NULL, PRIMARY KEY (`transaction_id`, `tag_id`), INDEX `transaction_tag_tag_id` (`tag_id`), CONSTRAINT `transaction_tag_tag_id` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, CONSTRAINT `transaction_tag_transaction_id` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
