// Code generated by MockGen. DO NOT EDIT.
// Source: request_target.go

// Package mock_model is a generated GoMock package.
package mock_model

import (
	gomock "github.com/golang/mock/gomock"
)

// MockRequestTargetRepository is a mock of RequestTargetRepository interface.
type MockRequestTargetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRequestTargetRepositoryMockRecorder
}

// MockRequestTargetRepositoryMockRecorder is the mock recorder for MockRequestTargetRepository.
type MockRequestTargetRepositoryMockRecorder struct {
	mock *MockRequestTargetRepository
}

// NewMockRequestTargetRepository creates a new mock instance.
func NewMockRequestTargetRepository(ctrl *gomock.Controller) *MockRequestTargetRepository {
	mock := &MockRequestTargetRepository{ctrl: ctrl}
	mock.recorder = &MockRequestTargetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestTargetRepository) EXPECT() *MockRequestTargetRepositoryMockRecorder {
	return m.recorder
}
