// Code generated by MockGen. DO NOT EDIT.
// Source: tag.go

// Package mock_model is a generated GoMock package.
package mock_model

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	ent "github.com/traPtitech/Jomon/ent"
	reflect "reflect"
)

// MockTagRepository is a mock of TagRepository interface
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// GetTags mocks base method
func (m *MockTagRepository) GetTags(ctx context.Context) ([]*ent.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", ctx)
	ret0, _ := ret[0].([]*ent.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags
func (mr *MockTagRepositoryMockRecorder) GetTags(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockTagRepository)(nil).GetTags), ctx)
}

// CreateTag mocks base method
func (m *MockTagRepository) CreateTag(ctx context.Context, name, description string) (*ent.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, name, description)
	ret0, _ := ret[0].(*ent.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag
func (mr *MockTagRepositoryMockRecorder) CreateTag(ctx, name, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockTagRepository)(nil).CreateTag), ctx, name, description)
}

// GetTag mocks base method
func (m *MockTagRepository) GetTag(ctx context.Context, tagID uuid.UUID) (*ent.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTag", ctx, tagID)
	ret0, _ := ret[0].(*ent.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTag indicates an expected call of GetTag
func (mr *MockTagRepositoryMockRecorder) GetTag(ctx, tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTag", reflect.TypeOf((*MockTagRepository)(nil).GetTag), ctx, tagID)
}

// UpdateTag mocks base method
func (m *MockTagRepository) UpdateTag(ctx context.Context, tagID uuid.UUID, name, description string) (*ent.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTag", ctx, tagID, name, description)
	ret0, _ := ret[0].(*ent.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTag indicates an expected call of UpdateTag
func (mr *MockTagRepositoryMockRecorder) UpdateTag(ctx, tagID, name, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockTagRepository)(nil).UpdateTag), ctx, tagID, name, description)
}

// GetTagTransactions mocks base method
func (m *MockTagRepository) GetTagTransactions(ctx context.Context, tag *ent.Tag) ([]*ent.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagTransactions", ctx, tag)
	ret0, _ := ret[0].([]*ent.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagTransactions indicates an expected call of GetTagTransactions
func (mr *MockTagRepositoryMockRecorder) GetTagTransactions(ctx, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagTransactions", reflect.TypeOf((*MockTagRepository)(nil).GetTagTransactions), ctx, tag)
}

// GetTagRequests mocks base method
func (m *MockTagRepository) GetTagRequests(ctx context.Context, tag *ent.Tag) ([]*ent.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagRequests", ctx, tag)
	ret0, _ := ret[0].([]*ent.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagRequests indicates an expected call of GetTagRequests
func (mr *MockTagRepositoryMockRecorder) GetTagRequests(ctx, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagRequests", reflect.TypeOf((*MockTagRepository)(nil).GetTagRequests), ctx, tag)
}

// DeleteTag mocks base method
func (m *MockTagRepository) DeleteTag(ctx context.Context, tag *ent.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", ctx, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag
func (mr *MockTagRepositoryMockRecorder) DeleteTag(ctx, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockTagRepository)(nil).DeleteTag), ctx, tag)
}
