// Code generated by entc, DO NOT EDIT.

package transactiontag

const (
	// Label holds the string label denoting the transactiontag type in the database.
	Label = "transaction_tag"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeTransaction holds the string denoting the transaction edge name in mutations.
	EdgeTransaction = "transaction"
	// EdgeTag holds the string denoting the tag edge name in mutations.
	EdgeTag = "tag"
	// Table holds the table name of the transactiontag in the database.
	Table = "transaction_tags"
	// TransactionTable is the table the holds the transaction relation/edge.
	TransactionTable = "transaction_tags"
	// TransactionInverseTable is the table name for the Transaction entity.
	// It exists in this package in order to avoid circular dependency with the "transaction" package.
	TransactionInverseTable = "transactions"
	// TransactionColumn is the table column denoting the transaction relation/edge.
	TransactionColumn = "transaction_tag"
	// TagTable is the table the holds the tag relation/edge.
	TagTable = "transaction_tags"
	// TagInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagInverseTable = "tags"
	// TagColumn is the table column denoting the tag relation/edge.
	TagColumn = "tag_transaction_tag"
)

// Columns holds all SQL columns for transactiontag fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "transaction_tags"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"tag_transaction_tag",
	"transaction_tag",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
