// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/traPtitech/Jomon/ent/application"
	"github.com/traPtitech/Jomon/ent/applicationstatus"
	"github.com/traPtitech/Jomon/ent/predicate"
	"github.com/traPtitech/Jomon/ent/user"
)

// ApplicationStatusUpdate is the builder for updating ApplicationStatus entities.
type ApplicationStatusUpdate struct {
	config
	hooks    []Hook
	mutation *ApplicationStatusMutation
}

// Where appends a list predicates to the ApplicationStatusUpdate builder.
func (asu *ApplicationStatusUpdate) Where(ps ...predicate.ApplicationStatus) *ApplicationStatusUpdate {
	asu.mutation.Where(ps...)
	return asu
}

// SetStatus sets the "status" field.
func (asu *ApplicationStatusUpdate) SetStatus(a applicationstatus.Status) *ApplicationStatusUpdate {
	asu.mutation.SetStatus(a)
	return asu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (asu *ApplicationStatusUpdate) SetNillableStatus(a *applicationstatus.Status) *ApplicationStatusUpdate {
	if a != nil {
		asu.SetStatus(*a)
	}
	return asu
}

// SetCreatedAt sets the "created_at" field.
func (asu *ApplicationStatusUpdate) SetCreatedAt(t time.Time) *ApplicationStatusUpdate {
	asu.mutation.SetCreatedAt(t)
	return asu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (asu *ApplicationStatusUpdate) SetNillableCreatedAt(t *time.Time) *ApplicationStatusUpdate {
	if t != nil {
		asu.SetCreatedAt(*t)
	}
	return asu
}

// SetApplicationID sets the "application" edge to the Application entity by ID.
func (asu *ApplicationStatusUpdate) SetApplicationID(id uuid.UUID) *ApplicationStatusUpdate {
	asu.mutation.SetApplicationID(id)
	return asu
}

// SetApplication sets the "application" edge to the Application entity.
func (asu *ApplicationStatusUpdate) SetApplication(a *Application) *ApplicationStatusUpdate {
	return asu.SetApplicationID(a.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (asu *ApplicationStatusUpdate) SetUserID(id uuid.UUID) *ApplicationStatusUpdate {
	asu.mutation.SetUserID(id)
	return asu
}

// SetUser sets the "user" edge to the User entity.
func (asu *ApplicationStatusUpdate) SetUser(u *User) *ApplicationStatusUpdate {
	return asu.SetUserID(u.ID)
}

// Mutation returns the ApplicationStatusMutation object of the builder.
func (asu *ApplicationStatusUpdate) Mutation() *ApplicationStatusMutation {
	return asu.mutation
}

// ClearApplication clears the "application" edge to the Application entity.
func (asu *ApplicationStatusUpdate) ClearApplication() *ApplicationStatusUpdate {
	asu.mutation.ClearApplication()
	return asu
}

// ClearUser clears the "user" edge to the User entity.
func (asu *ApplicationStatusUpdate) ClearUser() *ApplicationStatusUpdate {
	asu.mutation.ClearUser()
	return asu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (asu *ApplicationStatusUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, asu.sqlSave, asu.mutation, asu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (asu *ApplicationStatusUpdate) SaveX(ctx context.Context) int {
	affected, err := asu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (asu *ApplicationStatusUpdate) Exec(ctx context.Context) error {
	_, err := asu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asu *ApplicationStatusUpdate) ExecX(ctx context.Context) {
	if err := asu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asu *ApplicationStatusUpdate) check() error {
	if v, ok := asu.mutation.Status(); ok {
		if err := applicationstatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ApplicationStatus.status": %w`, err)}
		}
	}
	if asu.mutation.ApplicationCleared() && len(asu.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApplicationStatus.application"`)
	}
	if asu.mutation.UserCleared() && len(asu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApplicationStatus.user"`)
	}
	return nil
}

func (asu *ApplicationStatusUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := asu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(applicationstatus.Table, applicationstatus.Columns, sqlgraph.NewFieldSpec(applicationstatus.FieldID, field.TypeUUID))
	if ps := asu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := asu.mutation.Status(); ok {
		_spec.SetField(applicationstatus.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := asu.mutation.CreatedAt(); ok {
		_spec.SetField(applicationstatus.FieldCreatedAt, field.TypeTime, value)
	}
	if asu.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   applicationstatus.ApplicationTable,
			Columns: []string{applicationstatus.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := asu.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   applicationstatus.ApplicationTable,
			Columns: []string{applicationstatus.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if asu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   applicationstatus.UserTable,
			Columns: []string{applicationstatus.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := asu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   applicationstatus.UserTable,
			Columns: []string{applicationstatus.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, asu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{applicationstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	asu.mutation.done = true
	return n, nil
}

// ApplicationStatusUpdateOne is the builder for updating a single ApplicationStatus entity.
type ApplicationStatusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApplicationStatusMutation
}

// SetStatus sets the "status" field.
func (asuo *ApplicationStatusUpdateOne) SetStatus(a applicationstatus.Status) *ApplicationStatusUpdateOne {
	asuo.mutation.SetStatus(a)
	return asuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (asuo *ApplicationStatusUpdateOne) SetNillableStatus(a *applicationstatus.Status) *ApplicationStatusUpdateOne {
	if a != nil {
		asuo.SetStatus(*a)
	}
	return asuo
}

// SetCreatedAt sets the "created_at" field.
func (asuo *ApplicationStatusUpdateOne) SetCreatedAt(t time.Time) *ApplicationStatusUpdateOne {
	asuo.mutation.SetCreatedAt(t)
	return asuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (asuo *ApplicationStatusUpdateOne) SetNillableCreatedAt(t *time.Time) *ApplicationStatusUpdateOne {
	if t != nil {
		asuo.SetCreatedAt(*t)
	}
	return asuo
}

// SetApplicationID sets the "application" edge to the Application entity by ID.
func (asuo *ApplicationStatusUpdateOne) SetApplicationID(id uuid.UUID) *ApplicationStatusUpdateOne {
	asuo.mutation.SetApplicationID(id)
	return asuo
}

// SetApplication sets the "application" edge to the Application entity.
func (asuo *ApplicationStatusUpdateOne) SetApplication(a *Application) *ApplicationStatusUpdateOne {
	return asuo.SetApplicationID(a.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (asuo *ApplicationStatusUpdateOne) SetUserID(id uuid.UUID) *ApplicationStatusUpdateOne {
	asuo.mutation.SetUserID(id)
	return asuo
}

// SetUser sets the "user" edge to the User entity.
func (asuo *ApplicationStatusUpdateOne) SetUser(u *User) *ApplicationStatusUpdateOne {
	return asuo.SetUserID(u.ID)
}

// Mutation returns the ApplicationStatusMutation object of the builder.
func (asuo *ApplicationStatusUpdateOne) Mutation() *ApplicationStatusMutation {
	return asuo.mutation
}

// ClearApplication clears the "application" edge to the Application entity.
func (asuo *ApplicationStatusUpdateOne) ClearApplication() *ApplicationStatusUpdateOne {
	asuo.mutation.ClearApplication()
	return asuo
}

// ClearUser clears the "user" edge to the User entity.
func (asuo *ApplicationStatusUpdateOne) ClearUser() *ApplicationStatusUpdateOne {
	asuo.mutation.ClearUser()
	return asuo
}

// Where appends a list predicates to the ApplicationStatusUpdate builder.
func (asuo *ApplicationStatusUpdateOne) Where(ps ...predicate.ApplicationStatus) *ApplicationStatusUpdateOne {
	asuo.mutation.Where(ps...)
	return asuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (asuo *ApplicationStatusUpdateOne) Select(field string, fields ...string) *ApplicationStatusUpdateOne {
	asuo.fields = append([]string{field}, fields...)
	return asuo
}

// Save executes the query and returns the updated ApplicationStatus entity.
func (asuo *ApplicationStatusUpdateOne) Save(ctx context.Context) (*ApplicationStatus, error) {
	return withHooks(ctx, asuo.sqlSave, asuo.mutation, asuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (asuo *ApplicationStatusUpdateOne) SaveX(ctx context.Context) *ApplicationStatus {
	node, err := asuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (asuo *ApplicationStatusUpdateOne) Exec(ctx context.Context) error {
	_, err := asuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asuo *ApplicationStatusUpdateOne) ExecX(ctx context.Context) {
	if err := asuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asuo *ApplicationStatusUpdateOne) check() error {
	if v, ok := asuo.mutation.Status(); ok {
		if err := applicationstatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ApplicationStatus.status": %w`, err)}
		}
	}
	if asuo.mutation.ApplicationCleared() && len(asuo.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApplicationStatus.application"`)
	}
	if asuo.mutation.UserCleared() && len(asuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApplicationStatus.user"`)
	}
	return nil
}

func (asuo *ApplicationStatusUpdateOne) sqlSave(ctx context.Context) (_node *ApplicationStatus, err error) {
	if err := asuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(applicationstatus.Table, applicationstatus.Columns, sqlgraph.NewFieldSpec(applicationstatus.FieldID, field.TypeUUID))
	id, ok := asuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApplicationStatus.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := asuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, applicationstatus.FieldID)
		for _, f := range fields {
			if !applicationstatus.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != applicationstatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := asuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := asuo.mutation.Status(); ok {
		_spec.SetField(applicationstatus.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := asuo.mutation.CreatedAt(); ok {
		_spec.SetField(applicationstatus.FieldCreatedAt, field.TypeTime, value)
	}
	if asuo.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   applicationstatus.ApplicationTable,
			Columns: []string{applicationstatus.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := asuo.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   applicationstatus.ApplicationTable,
			Columns: []string{applicationstatus.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if asuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   applicationstatus.UserTable,
			Columns: []string{applicationstatus.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := asuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   applicationstatus.UserTable,
			Columns: []string{applicationstatus.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApplicationStatus{config: asuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, asuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{applicationstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	asuo.mutation.done = true
	return _node, nil
}
