// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/traPtitech/Jomon/ent/groupbudget"
	"github.com/traPtitech/Jomon/ent/predicate"
)

// GroupBudgetDelete is the builder for deleting a GroupBudget entity.
type GroupBudgetDelete struct {
	config
	hooks    []Hook
	mutation *GroupBudgetMutation
}

// Where adds a new predicate to the GroupBudgetDelete builder.
func (gbd *GroupBudgetDelete) Where(ps ...predicate.GroupBudget) *GroupBudgetDelete {
	gbd.mutation.predicates = append(gbd.mutation.predicates, ps...)
	return gbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gbd *GroupBudgetDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gbd.hooks) == 0 {
		affected, err = gbd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupBudgetMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gbd.mutation = mutation
			affected, err = gbd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gbd.hooks) - 1; i >= 0; i-- {
			mut = gbd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gbd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gbd *GroupBudgetDelete) ExecX(ctx context.Context) int {
	n, err := gbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gbd *GroupBudgetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: groupbudget.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groupbudget.FieldID,
			},
		},
	}
	if ps := gbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, gbd.driver, _spec)
}

// GroupBudgetDeleteOne is the builder for deleting a single GroupBudget entity.
type GroupBudgetDeleteOne struct {
	gbd *GroupBudgetDelete
}

// Exec executes the deletion query.
func (gbdo *GroupBudgetDeleteOne) Exec(ctx context.Context) error {
	n, err := gbdo.gbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupbudget.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gbdo *GroupBudgetDeleteOne) ExecX(ctx context.Context) {
	gbdo.gbd.ExecX(ctx)
}
