// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/traPtitech/Jomon/ent/request"
	"github.com/traPtitech/Jomon/ent/requeststatus"
)

// RequestStatusCreate is the builder for creating a RequestStatus entity.
type RequestStatusCreate struct {
	config
	mutation *RequestStatusMutation
	hooks    []Hook
}

// SetCreatedBy sets the "created_by" field.
func (rsc *RequestStatusCreate) SetCreatedBy(s string) *RequestStatusCreate {
	rsc.mutation.SetCreatedBy(s)
	return rsc
}

// SetRequestID sets the "request_id" field.
func (rsc *RequestStatusCreate) SetRequestID(i int) *RequestStatusCreate {
	rsc.mutation.SetRequestID(i)
	return rsc
}

// SetStatus sets the "status" field.
func (rsc *RequestStatusCreate) SetStatus(r requeststatus.Status) *RequestStatusCreate {
	rsc.mutation.SetStatus(r)
	return rsc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rsc *RequestStatusCreate) SetNillableStatus(r *requeststatus.Status) *RequestStatusCreate {
	if r != nil {
		rsc.SetStatus(*r)
	}
	return rsc
}

// SetReason sets the "reason" field.
func (rsc *RequestStatusCreate) SetReason(s string) *RequestStatusCreate {
	rsc.mutation.SetReason(s)
	return rsc
}

// SetCreatedAt sets the "created_at" field.
func (rsc *RequestStatusCreate) SetCreatedAt(t time.Time) *RequestStatusCreate {
	rsc.mutation.SetCreatedAt(t)
	return rsc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rsc *RequestStatusCreate) SetNillableCreatedAt(t *time.Time) *RequestStatusCreate {
	if t != nil {
		rsc.SetCreatedAt(*t)
	}
	return rsc
}

// SetRequest sets the "request" edge to the Request entity.
func (rsc *RequestStatusCreate) SetRequest(r *Request) *RequestStatusCreate {
	return rsc.SetRequestID(r.ID)
}

// Mutation returns the RequestStatusMutation object of the builder.
func (rsc *RequestStatusCreate) Mutation() *RequestStatusMutation {
	return rsc.mutation
}

// Save creates the RequestStatus in the database.
func (rsc *RequestStatusCreate) Save(ctx context.Context) (*RequestStatus, error) {
	var (
		err  error
		node *RequestStatus
	)
	rsc.defaults()
	if len(rsc.hooks) == 0 {
		if err = rsc.check(); err != nil {
			return nil, err
		}
		node, err = rsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RequestStatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rsc.check(); err != nil {
				return nil, err
			}
			rsc.mutation = mutation
			node, err = rsc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rsc.hooks) - 1; i >= 0; i-- {
			mut = rsc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rsc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rsc *RequestStatusCreate) SaveX(ctx context.Context) *RequestStatus {
	v, err := rsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (rsc *RequestStatusCreate) defaults() {
	if _, ok := rsc.mutation.Status(); !ok {
		v := requeststatus.DefaultStatus
		rsc.mutation.SetStatus(v)
	}
	if _, ok := rsc.mutation.CreatedAt(); !ok {
		v := requeststatus.DefaultCreatedAt()
		rsc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rsc *RequestStatusCreate) check() error {
	if _, ok := rsc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New("ent: missing required field \"created_by\"")}
	}
	if _, ok := rsc.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New("ent: missing required field \"request_id\"")}
	}
	if _, ok := rsc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New("ent: missing required field \"status\"")}
	}
	if v, ok := rsc.mutation.Status(); ok {
		if err := requeststatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf("ent: validator failed for field \"status\": %w", err)}
		}
	}
	if _, ok := rsc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New("ent: missing required field \"reason\"")}
	}
	if _, ok := rsc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New("ent: missing required field \"created_at\"")}
	}
	if _, ok := rsc.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request", err: errors.New("ent: missing required edge \"request\"")}
	}
	return nil
}

func (rsc *RequestStatusCreate) sqlSave(ctx context.Context) (*RequestStatus, error) {
	_node, _spec := rsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rsc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (rsc *RequestStatusCreate) createSpec() (*RequestStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestStatus{config: rsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: requeststatus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: requeststatus.FieldID,
			},
		}
	)
	if value, ok := rsc.mutation.CreatedBy(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: requeststatus.FieldCreatedBy,
		})
		_node.CreatedBy = value
	}
	if value, ok := rsc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: requeststatus.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := rsc.mutation.Reason(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: requeststatus.FieldReason,
		})
		_node.Reason = value
	}
	if value, ok := rsc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: requeststatus.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := rsc.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   requeststatus.RequestTable,
			Columns: []string{requeststatus.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: request.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RequestStatusCreateBulk is the builder for creating many RequestStatus entities in bulk.
type RequestStatusCreateBulk struct {
	config
	builders []*RequestStatusCreate
}

// Save creates the RequestStatus entities in the database.
func (rscb *RequestStatusCreateBulk) Save(ctx context.Context) ([]*RequestStatus, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rscb.builders))
	nodes := make([]*RequestStatus, len(rscb.builders))
	mutators := make([]Mutator, len(rscb.builders))
	for i := range rscb.builders {
		func(i int, root context.Context) {
			builder := rscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rscb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rscb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rscb *RequestStatusCreateBulk) SaveX(ctx context.Context) []*RequestStatus {
	v, err := rscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
