FROM golang:1.13.5-alpine as build
ENV DOCKERIZE_VERSION v0.6.1
ENV CGO_ENABLED 0
ARG GO_BUILD_TAGS=''

RUN echo $GO_BUILD_TAGS


WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/Jomon